web_controllers:
    resource: ../../src/Controller/web/
    type: annotation
    name_prefix: web_
 
admin_controllers:
    resource: ../../src/Controller/admin/
    type: annotation
    name_prefix: admin_

profile_controllers:
    resource: ../../src/Controller/profile/
    type: annotation
    name_prefix: profile_

kernel:
    resource: ../../src/Kernel.php
    type: annotation
