web_controllers:
    resource: ../../src/Controller/web/
    type: annotation
    name_prefix: web_
    prefix: '/{_locale}'
    requirements:
        _locale: '%app.locales%'
 
admin_controllers:
    prefix: /admin
    resource: ../../src/Controller/admin/
    type: annotation
    name_prefix: admin_

profile_controllers:
    prefix: '/{_locale}/profile'
    resource: ../../src/Controller/profile/
    type: annotation
    name_prefix: profile_
    requirements:
        _locale: '%app.locales%'

restAPI_controllers:
    prefix: /rest
    resource: ../../src/Controller/RestApi/
    type: annotation
    name_prefix: rest_
kernel:
    resource: ../../src/Kernel.php
    type: annotation

web_redirect_index:
    path: /
    controller: App\Controller\web\LocaleRedirectController
    defaults:
        route: 'web_index'