web_controllers:
    resource: ../../src/Controller/web/
    type: annotation
    name_prefix: web_
 
admin_controllers:
    prefix: /admin
    resource: ../../src/Controller/admin/
    type: annotation
    name_prefix: admin_

profile_controllers:
    prefix: /profile
    resource: ../../src/Controller/profile/
    type: annotation
    name_prefix: profile_

restAPI_controllers:
    prefix: /rest
    resource: ../../src/Controller/RestApi/
    type: annotation
    name_prefix: rest_
kernel:
    resource: ../../src/Kernel.php
    type: annotation
