#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
  path: /login
  controller: App\Controller\SecurityController::login
  defaults:
    route: 'login'

index:
  path: /
  controller: App\Controller\web\IndexController